import {StyleSheet} from 'react-native';
import colors from '../utils/colors';

export const fontStyle = StyleSheet.create({
  h1: {
    fontSize: 20,
    fontFamily: 'System',
    fontWeight: '500',
    lineHeight: 22,
    color: 'white',
  },
  h2: {
    fontSize: 18,
    fontFamily: 'System',
    fontWeight: '500',
    lineHeight: 20,
    color: 'white',
  },
  h3: {
    fontSize: 16,
    fontFamily: 'System',
    fontWeight: '500',
    lineHeight: 18,
    color: 'white',
  },
  h4: {
    fontSize: 14,
    fontFamily: 'System',
    fontWeight: '500',
    lineHeight: 16,
    color: 'white',
  },
  h5: {
    fontSize: 12,
    fontFamily: 'System',
    fontWeight: '500',
    lineHeight: 14,
    color: 'white',
  },
  h6: {
    fontSize: 10,
    fontFamily: 'System',
    fontWeight: '500',
    lineHeight: 12,
    color: 'white',
  },
  h9: {
    fontSize: 24,
    fontFamily: 'System',
    fontWeight: '500',
    lineHeight: 26,
    color: 'white',
  },
  h10: {
    fontSize: 26,
    fontFamily: 'System',
    fontWeight: '500',
    lineHeight: 28,
    color: 'white',
  },
  h11: {
    fontSize: 28,
    fontFamily: 'System',
    fontWeight: '500',
    lineHeight: 30,
    color: 'white',
  },
  h12: {
    fontSize: 30,
    fontFamily: 'System',
    fontWeight: '500',
    lineHeight: 32,
    color: 'white',
  },
  body1: {
    fontSize: 20,
    fontFamily: 'System',
    fontWeight: 'normal',
    lineHeight: 22,
    color: 'white',
  },
  body2: {
    fontSize: 18,
    fontFamily: 'System',
    fontWeight: 'normal',
    lineHeight: 20,
    color: 'white',
  },
  body3: {
    fontSize: 16,
    fontFamily: 'System',
    fontWeight: 'normal',
    lineHeight: 18,
    color: 'white',
  },
  body4: {
    fontSize: 14,
    fontFamily: 'System',
    fontWeight: 'normal',
    lineHeight: 16,
    color: 'white',
  },
  body5: {
    fontSize: 12,
    fontFamily: 'System',
    fontWeight: 'normal',
    lineHeight: 14,
    color: 'white',
  },
  body6: {
    fontSize: 10,
    fontFamily: 'System',
    fontWeight: 'normal',
    lineHeight: 12,
    color: 'white',
  },
  button1: {
    fontSize: 20,
    fontFamily: 'System',
    fontWeight: 'bold',
    lineHeight: 22,
    color: 'white',
    textTransform: 'uppercase',
  },
  button2: {
    fontSize: 18,
    fontFamily: 'System',
    fontWeight: 'bold',
    lineHeight: 20,
    color: 'white',
    textTransform: 'uppercase',
  },
  button3: {
    fontSize: 16,
    fontFamily: 'System',
    fontWeight: 'bold',
    lineHeight: 18,
    color: 'white',
    textTransform: 'uppercase',
  },
  button4: {
    fontSize: 14,
    fontFamily: 'System',
    fontWeight: 'bold',
    lineHeight: 16,
    color: 'white',
    textTransform: 'uppercase',
  },
  button5: {
    fontSize: 12,
    fontFamily: 'System',
    fontWeight: 'bold',
    lineHeight: 14,
    color: 'white',
    textTransform: 'uppercase',
  },
  button6: {
    fontSize: 10,
    fontFamily: 'System',
    fontWeight: 'bold',
    lineHeight: 12,
    color: 'white',
    textTransform: 'uppercase',
  },
});
